version: '2.1'

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - discovery.seed_hosts=elasticsearch2,elasticsearch3
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    volumes:
      - elastic1:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      elastic:
        aliases:
          - es1
    ports:
      - 9200:9200
    mem_reservation: 4g

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - discovery.seed_hosts=elasticsearch1,elasticsearch3
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    volumes:
      - elastic2:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      elastic:
        aliases:
          - es2
    mem_reservation: 4g

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    volumes:
      - elastic3:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      elastic:
        aliases:
          - es3
    mem_reservation: 4g

  snowstorm:
    image: snomedinternational/snowstorm:latest
    container_name: snowstorm
    restart: always
    depends_on:
      elasticsearch1:
        condition: service_healthy
    entrypoint: java -Xms2g -Xmx4g --add-opens java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -cp @/app/jib-classpath-file org.snomed.snowstorm.SnowstormApplication --elasticsearch.urls=http://es1:9200
    networks:
      elastic:
        aliases:
         - snowstorm
    ports:
      - 8080:8080

  browser:
    image: snomedinternational/snomedct-browser:latest
    container_name: browser
    depends_on:
      - snowstorm
    links:
      - snowstorm:snowstorm
    networks:
      - elastic
    environment:
      - API_HOST=http://snowstorm:8080/
    ports:
      - 80:80
    restart: always

networks:
  elastic:

volumes:
  elastic1:
  elastic2:
  elastic3:
  elastic:
